pipeline {
    agent {
      docker
      {
        image 'python:alpine3.15'
      }
    }
    stages {
        stage('build') {
            steps {
                sh 'python --version'
            }
        }
    }
}
