pipeline {
    agent none
    stages {
        stage('build') {
            when {
                changeset "**/vote/**"
                branch 'main'
            }
            agent {
                docker
                {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            steps {
                echo 'Installing requirements for vote app'
                    dir('vote'){
                        sh 'pip install -r requirements.txt'
                    }
            }
        }
        stage('test') {
            when {
                branch 'main'
                changeset "**/vote/**"
            }
            agent {
                docker
                {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            steps {
                echo 'Running unit tests on vote app'
                    dir('vote'){
                        sh 'pip install -r requirements.txt'
                        sh 'nosetests -v'
                    }
                }
        }
        stage('docker-package') {
            agent any
            when {
                branch 'main'
                changeset "**/vote/**"
            }
            steps {
                echo 'Packaging vote app in docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        def customImage = docker.build("fredflev/vote:v${env.BUILD_ID}", "./vote")
                        customImage.push()
                        customImage.push("${env.BRANCH_NAME}")
                        customImage.push("latest")
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'End of the vote App pipeline'
        }
        failure {
            slackSend (color: "danger", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
            slackSend (color: "good", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
