version: "3.7"

services:

  integration:
    build: ./
    networks:
      - integration

  vote:
    build: ../
    ports: [ "80" ]
    depends_on:
      - redis
    networks:
      - integration

  redis:
    image: redis:alpine
    ports: [ "6379" ]
    networks:
      - integration

networks:
  integration:
