apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: default
spec:
  ports:
    - name: "4000"
      nodePort: 30501
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: result
  type: NodePort
