apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 3
  selector:
    matchLabels:
      app: result
  strategy: {}
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: fredflev/result:main
          name: result
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
