apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: default
spec:
  ports:
    - name: "80"
      nodePort: 30500
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vote
  type: NodePort
